### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/NonlinearNormalForm.jl#4]
In GTPSA:
- [x] Move layer 2 implementations of "map" methods out of GTPSA and into this package? (Yes but then "parameters" in GTPSA.jl are meaningless, which might be okay, would have to move into this package, so unsure)
- [x] Allow changing Descriptors when number variables/parameters also changes? no for now
- [x] Documentation cleanup (fixing "Syntax" parts of gjh, etc)
- [x] Make TPSs callable for nicer evaluation syntax and also composition

Both:
- [x] **SizedVectors required (not isbits) and confirmed is slower in tracking than regular vectors.** Consider use of MVector/SVector for map fields. This is faster for small array sizes but concatenation current requires one to include all parameters in vector so may be slower for large number of parameters. Would need to Modify all lower level functions in GTPSA to also accept MVector or SVector (dense)

In NonlinearNormalForm
- [x] **cleaned** Probe ctor cleanup (all kwarg? but need number vars. MVectors + numvars in type. do not require v)
- [x] **Probe for both types of tracking**How to deal with Probes? Should I overload indexing for probe struct to automatically set scalar part?
- [x] Map ctor cleanup
- [x] Map operators: \circ, ^, +, -
- [x] (Bi)quaternion implementation
- [x] Add ref column to map output
- [x] Probe cannot just take a phase space ray... need to fix this. Etiennes way is to set x0 with scalar part of TPSA map and keep scalar part in map
